# Site settings
title: Miles Johnson - Technical Writing Portfolio
url: "https://milescjohnson.github.io"
baseurl: "" # leave empty for user/organization pages

# Author info
author:
  - Miles Johnson <m.milesjohnson@gmail.com>
 # email: m.milesjohnson@gmail.com
 # github: milescjohnson
 # linkedin: miles-c-johnson
  
# Theme
theme: minimal

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (GitHub Pagesâ€“approved)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  # date_format: "%b %-d, %Y" # uncomment to customize the date format
  skin: "classic" # change to 'dark', 'solarized', etc. if you have the skin files
  social_links:
    linkedin: miles-c-johnson # Replace with your Twitter username
    github: milescjohnson # Replace with your GitHub username
    # You can add more social links here, e.g. linkedin: yourusername

  header_pages:
    - index.md
    - contact.md
    - resume.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

# Exclude from build
exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock
